### ISSUE TITLE
Question about online demo.

### ISSUE THREAD

**Issue by Lzshanshan** [DepthAnything/Depth-Anything-V2#1]
Hello,

Thanks for this amazing work! When I downloaded the 16-bit raw output and wanted to convert it to 3D point cloud, I noticed that it can be considered as disparity. Is the following operation to take the inverse of data and then scale it?

When scaling it, can I use the corresponding raw depth map that is along with the input RGB image?

Thanks for your time and patience.

Zhenshan

**Comment by LiheYoung** [comment]
Hi, if you want to convert the image to point clouds, you can try our [metric depth models](https://github.com/DepthAnything/Depth-Anything-V2/tree/main/metric_depth) and the [depth_to_pointcloud.py](https://github.com/DepthAnything/Depth-Anything-V2/blob/main/metric_depth/depth_to_pointcloud.py) in it
