### ISSUE TITLE
the precision of infering result

### ISSUE THREAD

**Issue by SoulProficiency** [DepthAnything/Depth-Anything-V2#114]
using the same image,vitb is totally a black image but vitl can get a common depth map.

**Comment by heyoeyo** [comment]
If you get a fully black image, there's a good chance it's because one (or many) of the predicted values came out as infinity. You can potentially 'save' the rest of the data by just removing infinite values before any further processing.

You can do the following to remove infinite values:
```python
# Set infinite values to 0 to avoid further numerical errors
inf_mask = np.isinf(data)  # or use data.isinf() if it's a pytorch tensor
data[inf_mask] = 0
```

**Comment by SoulProficiency** [comment]
> ```python
> data[inf_mask] = 0
> ```

thanks a lot,its useful for me.(vitl is actually better than vits/vitb)

**Comment by heyoeyo** [comment]
> (vitl is actually better than vits/vitb)

I find the same is true! If you haven't already tried it, increasing the 'input size' script parameter can also improve the quality of the results significantly: `python run.py --input-size 798`
Sometimes vitb using a higher image size can produce nicer results than vitl (at the default size), while running just as fast.
