### ISSUE TITLE
after download the vkitti2 datasets and use dish_tran.sh to start train, the traing phase looks normal, but when test, the predicted depth vaules are all 0

### ISSUE THREAD

**Issue by visonpon** [DepthAnything/Depth-Anything-V2#135]

**Comment by nuanxinqing** [comment]
hi，您的下载下来的vkitti2数据集可以分享给我一下吗？谢谢！我的邮箱824265060@qq.com
不知为何我下载时跳转链接没有反应

**Comment by shilpaullas97** [comment]
Hi @visonpon ,

Did you fix this issue?
Are you getting expected results after training with vkitti dataset for metric depth?
