### ISSUE TITLE
DepthAnything v2 on Browser without any servers...

### ISSUE THREAD

**Issue by akbartus** [DepthAnything/Depth-Anything-V2#169]
Hi!

I just wanted to thank you for such a wonderful work and repository. I’ve been experimenting with DepthAnything v2 and have developed a browser-based implementation of it, powered by ONNX.

You can check it out here:

Github Repo: https://github.com/akbartus/DepthAnything-on-Browser
Interactive Demo: https://depthanything.glitch.me/interactive-dynamic.html

Feel free to share it on your page if you think it might be of interest!

**Comment by LiheYoung** [comment]
Thank you for your kind efforts!
