### ISSUE TITLE
Metric model question

### ISSUE THREAD

**Issue by ze-n-g** [DepthAnything/Depth-Anything-V2#196]
Hi, I got a bad result when I used the metric/run.py and depth_anything_v2_metric_vkitti_vitl.pth to test the outdoor image.
![image](https://github.com/user-attachments/assets/b9ae8a7c-0b21-4ac5-85ae-58684da66048)
However, the result is right for using run.py.
![image](https://github.com/user-attachments/assets/7d3eca1c-44a2-48ac-b662-134b67dbffdd)
The original image is here.
![Uploading image.png…]()

@duyuwen-duen, I have used your outdoor image, and I still got a bad result.
![image](https://github.com/user-attachments/assets/801caca8-8f18-4e21-bcf2-1d3663f8d45d)

Could someone provide some suggestions?

_Originally posted by @szhang963 in https://github.com/DepthAnything/Depth-Anything-V2/issues/93#issuecomment-2252420260_

**Comment by LiheYoung** [comment]
Hi, since the metric depth model is only trained on Virtual KITTI 2, it is not as robust as the relative depth models that are trained on large-scale data. Besides, for very far regions, *e.g.*, sky, the metric depth is very challenging to estimate.
