### ISSUE TITLE
TypeError: DepthAnythingV2.__init__() got an unexpected keyword argument 'max_depth'

### ISSUE THREAD

**Issue by Itachi-6** [DepthAnything/Depth-Anything-V2#205]
I am trying to get metric depth of an outdoor Image. So used the provided code:

`import cv2
import torch

from depth_anything_v2.dpt import DepthAnythingV2

model_configs = {
    'vits': {'encoder': 'vits', 'features': 64, 'out_channels': [48, 96, 192, 384]},
    'vitb': {'encoder': 'vitb', 'features': 128, 'out_channels': [96, 192, 384, 768]},
    'vitl': {'encoder': 'vitl', 'features': 256, 'out_channels': [256, 512, 1024, 1024]}
}

encoder = 'vitl' # or 'vits', 'vitb'
dataset = 'hypersim' # 'hypersim' for indoor model, 'vkitti' for outdoor model
max_depth = 20 # 20 for indoor model, 80 for outdoor model

model = DepthAnythingV2(**{**model_configs[encoder], 'max_depth': max_depth})
model.load_state_dict(torch.load(f'checkpoints/depth_anything_v2_metric_{dataset}_{encoder}.pth', map_location='cpu'))
model.eval()

raw_img = cv2.imread('your/image/path')
depth = model.infer_image(raw_img) # HxW depth map in meters in numpy`

Then I am getting this error. I even tried removing the metric depth here and kept 80.0 default while initializing. Please help.

**Comment by JarvisKevin** [comment]
which direction ara you in? Depth-Anything-V2/metric_depth?

**Comment by Itachi-6** [comment]
> which direction ara you in? Depth-Anything-V2/metric_depth?

Yes, and I am using the script provided there. May be the code has been changed a bit by removing the "max_depth" argument while initiating the model and they haven't updated the code Idk but it is saying this error. However, I removed the  argument and gave the max depth value in main python file where it was created and it worked.

**Comment by aditya-azad** [comment]
> > which direction ara you in? Depth-Anything-V2/metric_depth?
> 
> Yes, and I am using the script provided there. May be the code has been changed a bit by removing the "max_depth" argument while initiating the model and they haven't updated the code Idk but it is saying this error. However, I removed the argument and gave the max depth value in main python file where it was created and it worked.

You are using `DepthAnythingV2` in the root directory. You need to use `DepthAnythingV2` from `metric_depth` directory like so: `from metric_depth.depth_anything_v2.dpt import DepthAnythingV2`
