### ISSUE TITLE
license on  Large  model?cc-by-nc-4.0 No commercial  use ...?

### ISSUE THREAD

**Issue by mr-lab** [DepthAnything/Depth-Anything-V2#27]
Are images generated using  depth   From the Large  model as a Controlnet  guide  , not suitable for commercial use? 
I think many people will glaze over the small fine print in hugging face , and focus on the license  on github . 
Will the Giant Model have similar license ?

**Comment by LiheYoung** [comment]
Yes. In our V2, the ViT-small-based model can be used for commercial purpose, while other three models cannot.
