### ISSUE TITLE
metric_depth training

### ISSUE THREAD

**Issue by swing2331** [DepthAnything/Depth-Anything-V2#29]
Hi，I noticed that your metric_depth training code is run on multiple GPUs. Unfortunately, my device only has one GPU. Can I still complete the training?

**Comment by LiheYoung** [comment]
Yes, simply set `gpus=1` in the line: https://github.com/DepthAnything/Depth-Anything-V2/blob/c86af37112102f128f3db5ff190659d56b4305e2/metric_depth/dist_train.sh#L6
