### ISSUE TITLE
是否有度量深度估计的S模型提供。

### ISSUE THREAD

**Issue by gopin95** [DepthAnything/Depth-Anything-V2#3]
是否有度量深度估计的S模型提供。

**Comment by LiheYoung** [comment]
Hi, we will release metric depth models based on Depth-Anything-V2-Small and Base tomorrow.

**Comment by LiheYoung** [comment]
We have released [smaller metric depth models](https://github.com/DepthAnything/Depth-Anything-V2/tree/main/metric_depth#pre-trained-models).
