### ISSUE TITLE
Is the DINOv2 ViT-G encoder un-frozen when training teacher model?

### ISSUE THREAD

**Issue by Nik-V9** [DepthAnything/Depth-Anything-V2#37]
Hey folks, Thanks for the amazing work!

I was reading the paper regarding details for the training of the teacher model. It was not clear if the DINOv2 encoder is unfrozen when training the teacher model on the synthetic datasets?

Furthermore, similar to Depth Anything V1, is the DINOv2 encoder finetuned during the teacher-student model distillation?

Looking forward to your clarification!

**Comment by LiheYoung** [comment]
Hi, all DINOv2 models are fully fine-tuned in both V1 and V2.

**Comment by Nik-V9** [comment]
Thanks for the clarification!
