### ISSUE TITLE
pointcloud visualization

### ISSUE THREAD

**Issue by edgarriba** [DepthAnything/Depth-Anything-V2#39]
hi! is there any example or experiment that shows how the pointcloud looks like ?

**Comment by kaixin-bai** [comment]
The MDE task can only output 0-1 relative depth values, which cannot be converted to 3D information without the exact camera intrinsic and scale information, and I remember that the paper mentioned that if you want to convert to 3D you need to finetune on a dataset with scale information.

**Comment by edgarriba** [comment]
thanks!

**Comment by ducha-aiki** [comment]
Actually there is a metric depth version. Better than ZoeDepth, worse than Metric3D
https://github.com/DepthAnything/Depth-Anything-V2/tree/main/metric_depth
