### ISSUE TITLE
Is lstsq(Least Square) still working in depth-anythingV2?

### ISSUE THREAD

**Issue by zhongqiu1245** [DepthAnything/Depth-Anything-V2#43]
Hello, thank you for your amazing job!
Is lstsq(Least Square) still working in depth-anythingV2? https://github.com/LiheYoung/Depth-Anything/issues/72#issuecomment-1925462937
Or this formula is still right? https://github.com/LiheYoung/Depth-Anything/issues/72#issuecomment-1925569620
Thank you in advance.

**Comment by LiheYoung** [comment]
Yes, the formula should be the same for V1 and V2.

**Comment by zhongqiu1245** [comment]
thx！
