### ISSUE TITLE
how to get the grayscale output?

### ISSUE THREAD

**Issue by MistyDragon7** [DepthAnything/Depth-Anything-V2#44]
in the V1 pipeline on huggingface, we used to get a grayscale output. Can anyone tell me how we can get the grayscale output for the V2 model?

**Comment by LiheYoung** [comment]
Hi, we also provide the option to download the grayscale depth map in our V2 online demo.

**Comment by MistyDragon7** [comment]
yes, indeed. I am using your model for a project, and I would like to be able to have that grayscale depth map directly in my colab notebook, if you understand what I mean. right now, I am using the pipeline on huggingface for V1, I wanted to know how I can do this for V2. Thank You.

**Comment by LiheYoung** [comment]
We have added the grayscale option in our running script: https://github.com/DepthAnything/Depth-Anything-V2/blob/4b8b3e4bb029567a5fcb477eaa430620970f0977/run.py#L62-L63

**Comment by MistyDragon7** [comment]
so basically, I have to pass it as an argument with the run.py file? Or I guess I could directly just take that part of the code and remove the trinkets? Please let me know if I am correct. Thanks a Lot!
