### ISSUE TITLE
Are sparse depth map labels available for fine-tuning to get metric depth estimation？

### ISSUE THREAD

**Issue by Edric-star** [DepthAnything/Depth-Anything-V2#55]
Hi @LiheYoung, again loving your work! As the title mentioned, would it be ok that I use my sparse depth map labels (instead of dense) to fine-tune? My purpose is to get the estimation of my own datasets, I would really appreciate it if you could let me know.

**Comment by LiheYoung** [comment]
Yes, it is ok. You can simply ignore the loss in regions without labels.

**Comment by Edric-star** [comment]
> Yes, it is ok. You can simply ignore the loss in regions without labels.

Copy that, thanks!
