### ISSUE TITLE
The onnx2trt tutorial of Depth-Anything-v2.

### ISSUE THREAD

**Issue by zhujiajian98** [DepthAnything/Depth-Anything-V2#57]
Dear author, I appreciate your work very much, because the onnx2trt resources provided on the Internet are a bit cluttered, which is not conducive to novices to convert your model to tensorrt, so I have compiled a [repository](https://github.com/zhujiajian98/Depth-Anythingv2-TensorRT-python) that uses tensorrt8.5.2.2 to convert depth anything v2 from onnx to tensorrt, if you are interested here, you can also organize the relevant code of the repository into your repository in the future, thank you!

**Comment by LiheYoung** [comment]
Thank you! I will add this to our README in the next update.
