### ISSUE TITLE
Bad evaluation results.

### ISSUE THREAD

**Issue by indu1ge** [DepthAnything/Depth-Anything-V2#58]
Hi,

Thank you for your great efforts in building such a foundation MDE model. I downloaded the ViT-L model and conducted evaluations on the NYU test set. However, the evaluation result I obtained shows an AbsRel of 0.098, which is significantly different from the reported 0.045 in the paper. Could you please provide the corresponding evaluation code?

Thank you for your assistance.

**Comment by wangzerong** [comment]
I also encountered the same problem. The AbsRel on NYUD does not match the paper，but can match the Marigold's result with the same evaluation code.

**Comment by Xiaracto** [comment]
https://github.com/DepthAnything/Depth-Anything-V2/issues/88
