### ISSUE TITLE
Custom depth map output format

### ISSUE THREAD

**Issue by ThreeDeeJay** [DepthAnything/Depth-Anything-V2#70]
It'd be nice to be able to use Depth Anything V2 in [DepthViewer](https://github.com/parkchamchi/DepthViewer) (2D to 3D video converter/player for VR/3D displays), 
but [it only supports V1](https://github.com/parkchamchi/DepthViewer/issues/14#issuecomment-2183330929) using [this](https://github.com/ThreeDeeJay/DepthViewer/releases/latest). I'm particularly interested in 2D to 3D video/movie conversion, and considering it might not be possible get stable, realtime (like 24FPS) conversion using the highest quality models, the best alternative is to pre-cache the depth map for every frame beforehand.
Luckily, DepthViewer already has a cache format for videos, which is basically just a ZIP file containing every raw frame in [PGM](https://netpbm.sourceforge.net/doc/pgm.html)/[PFM](https://www.pauldebevec.com/Research/HDR/PFM/) format and some metadata.
![demo_cache](https://raw.githubusercontent.com/parkchamchi/DepthViewer/master/examples/demo_cache.png)
So could you please add an option to [run_video.py](https://github.com/DepthAnything/Depth-Anything-V2/blob/main/run_video.py) to output every depth frame into numbered PGM/PFM files, perhaps in a (probably solid) ZIP file?
Then we could just manually add a metadata file from a template to use it in DepthViewer 👀👌 

If you need a sample, here's [Wildlife](https://archive.org/download/WildlifeSampleVideo/Wildlife.wmv) and the [.depthviewer](https://github.com/user-attachments/files/16144270/Wildlife.wmv.MidasV21Small.05aefc9502534cac696a25e5020ae40abbc2a2bc918a9902a60673849a0857b4.depthviewer.zip) file generated by DepthViewer's built-in model.

**Comment by heyoeyo** [comment]
I'm not sure how likely it would be for such a specific/custom change top be added to the codebase, but it's relatively simple to make the modifications on your own local copy.

First, the current video runner doesn't include a frame index, so you'd have to add that in. You'd also want to create a folder to store the pgm files for each separate video (in case you process multiple videos, you don't want them overwriting each other). This can be done by adding some extra code to create the save folder path and start a frame counter just above the existing [while loop](https://github.com/DepthAnything/Depth-Anything-V2/blob/31dc97708961675ce6b3a8d8ffa729170a4aa273/run_video.py#L68), something like: 
```python
video_name = os.path.splitext(os.path.basename(filename))[0]
pgm_folder_path = os.path.join(args.outdir, video_name)
os.makedirs(pgm_folder_path, exist_ok=True)
frame_idx = 0
```

And then the only other change would be to save pgm files and update the frame counter. You can do this by adding some new lines just after the normalized [depth image](https://github.com/DepthAnything/Depth-Anything-V2/blob/31dc97708961675ce6b3a8d8ffa729170a4aa273/run_video.py#L76) is created:
```python
pgm_save_path = os.path.join(pgm_folder_path, f"{frame_idx:06}.pgm")
cv2.imwrite(pgm_save_path, depth)
frame_idx += 1
```

**Comment by ThreeDeeJay** [comment]
Thanks, I'll give it a shot when I get a chance
I made the changes on my fork https://github.com/ThreeDeeJay/Depth-Anything-V2/commit/271db9f0f18bc625ab6bf5eed7921c51cba4a9d1

**Comment by ThreeDeeJay** [comment]
Follow-up: it works!
Just had to [Remove leading zeroes from PGM filename
](https://github.com/ThreeDeeJay/Depth-Anything-V2/commit/b3bc24616cc203c1390b5d6296115d774f3a67f7)
Then I ran `python run_video.py --encoder vitl --video-path "path\to\Wildlife.wmv" --outdir Wildlife --pred-only --grayscale` and zipped PGM files in "path\to\Wildlife\Wildlife" along with [METADATA.txt](https://github.com/user-attachments/files/16449320/METADATA.txt) into `"%USERPROFILE%\AppData\LocalLow\parkchamchi\DepthViewer\depths\Wildlife.wmv.MidasV21Small.05aefc9502534cac696a25e5020ae40abbc2a2bc918a9902a60673849a0857b4.depthviewer"` file and voilà, Run DepthViewer and open Wildlife.wmv (or whatever file you're using)👌
Note: it says it's using MiDAS model but I'm just fooling DepthViewer into loading a pre-generated depth map from an unsupported model using a supported (built-in) model name so that there's no need for extra configuration.
@parkchamchi might wanna check this out 👀

Cross-eyed 3D screenshots of (realtime) playback in action:
![DepthViewer002_085](https://github.com/user-attachments/assets/f7ae0d75-6351-452f-8bb4-a5b71e649054)
![DepthViewer001_085](https://github.com/user-attachments/assets/2e9c5b77-4464-4c1c-b6be-d721b6ff50a6)
![DepthViewer004_085](https://github.com/user-attachments/assets/90ae2b45-5e41-4302-b269-9eea87b7a27b)
![DepthViewer003_085](https://github.com/user-attachments/assets/002a4fb7-2fc4-4531-93a3-596df8ca987d)
![DepthViewer006_085](https://github.com/user-attachments/assets/00ec5697-ed72-41f5-9911-e17de52b3c2a)
![DepthViewer005_085](https://github.com/user-attachments/assets/70dd8c7f-3f53-49b2-a68c-bd04743077a3)

Now I just gotta figure out how to improve performance because right now it's like 5FPS tops and CPU/GPU usage is pretty low 🤔 
also I think wrapping this into a script that zips and copies the file to the DepthViewer cache folder should be trivial.

**Comment by heyoeyo** [comment]
> figure out how to improve performance

I'm not sure if you mean the initial video recording or the 3D display, but if it's the video recording, I recently added a frame-by-frame saving feature to [my own video script](https://github.com/heyoeyo/muggled_dpt?tab=readme-ov-file#run-video-or-webcam), which I think tends to run faster (~2x) than the original depth-anything code (due to using float16 instead of 32). So maybe that can help if that's the slow part (my version also has the zero-padding that would need to be removed and saves in .png instead of .pgm, but that's easy to modify).

> script that zips

Yes this should be doable using the builtin `zipfile` library. It seems like you'd also need to fill out a bunch of fields to generate the metadata file, it looks like you already have a bunch of them (e.g. width/height/framerate) in your script, you can also get a timestamp and frame count using:
```python
import time
timestamp = int(time.time())
framecount = int(raw_video.get(cv2.CAP_PROP_FRAME_COUNT))
```

**Comment by heyoeyo** [comment]
> any idea if there's a better format to store depth map videos? ... really inefficient to store uncompressed ...

Yes the .pgm format is very inefficient (and may contribute to the slow playback if disk access is the bottleneck). Using .png is better but at the cost of needing to decompress it (i.e. more cpu work). Apparently `ffv1` is a codec that can do lossless video, I just tried this command:
`ffmpeg -framerate 30 -i %08d.png -c:v ffv1 output.mkv`
Using this on the pngs from my video script does create a video that's a bit smaller than the pngs themselves (4.6MB for the video vs 6.7MB for 180 pngs separately vs. 25.3MB for pgm), so that might be worth trying for smaller storage + speeding up disk access (should be quite significant actually).

> a tool that generates the left and right view on-the-fly to stream it in a local "server" so that other players can open it via URL

In theory yes... although I'm not sure about left/right views. I don't know if that's handled as two separate streams or some combined stream following constraints on the layout (I'm not familiar with VR standards at all). I've used this [mediamtx](https://github.com/bluenviron/mediamtx) server for creating 'live' video streams from files before, and I assume it would be possible to dynamically generate the frames on the fly to feed that stream. But I don't much more than that as far as how the VR formatting would be/could be handled .

**Comment by ThreeDeeJay** [comment]
I think besides lossless encoding, [it also needs higher bit depth](https://en.wikipedia.org/wiki/2D-plus-depth#Disadvantages) for an accurate depth map that's not constrained to the regular RGB range. Like, the Zoe model required a [PFM](https://microsoft.github.io/AirSim/pfm/) because apparently not even PGM preserved the full depth information.

But PFM is still an image format. I think ideally we'd want a lossless video codec that allows high enough bit depth *and* uses correlation between consecutive frames in case there's redundant data, to compress efficiently.

AVIF and HEIC both support depth maps and can be used to compress video (HEVC for the latter, I presume), so I wonder if we could get them working with DepthAnything 🤔 
![JXL](https://res.cloudinary.com/cloudinary-marketing/image/upload/w_700,c_fill,f_auto,q_auto,dpr_2.0/Web_Assets/blog/Battle-of-the-Codecs_fnl.png)

> although I'm not sure about left/right views. I don't know if that's handled as two separate streams or some combined stream following constraints on the layout (I'm not familiar with VR standards at all). 

The standard-ish 3D format is just SBS (side by side, left eye first) so if we could somehow create a live stream containing both views (displacing/warping source video pixels using the depth map) in a single frame for PotPlayer (or any other 3D/VR player) to split the image before showing them to each eye separately.

But the main challenge would be using a method that generates the left and views without losing too much quality.
Probably something like [SuperDepth3D](https://github.com/BlueSkyDefender/Depth3D), but to process the video stream before serving it for external players.

**Comment by heyoeyo** [comment]
> lossless video codec that allows high enough bit depth and uses correlation between consecutive frames in case there's redundant data, to compress efficiently

Considering the overall customness of this sort of data, a simple-ish solution might be to just encode the higher bits into the green and blue channels of the frame, and then use that ffv1 codec (or any other lossless codec) on the resulting frame. That would allow for up to 24-bit depth per frame (8 per RGB channel), which should be more than enough (actually just using the red/green channels for 16-bits [seems like it's probably good enough](https://github.com/DepthAnything/Depth-Anything-V2/issues/78)). Then it would just be a matter of properly un-packing the channel data on the other end.

**Comment by ThreeDeeJay** [comment]
That sounds like a good idea.
I wonder if we could take it a step further and reuse the source/2D video's compression/edges/motion vectors for the depth map.
So like a sort of [2D plus depth](https://en.wikipedia.org/wiki/2D-plus-depth) *and* [Delta](https://en.wikipedia.org/wiki/2D_plus_Delta) (stored separately/on a different track like the MVC/2nd view of Blu-ray 3Ds, which allows playing the main/AVC view in 2D for backwards compatibility)

That way maybe someone could eventually make a 3D player that auto-downloads depth maps generated by other people, using the video track hash, and it'd hopefully make it more legal to distribute movie depth maps to begin with, since you'd need to own the video file to decode the depth map. That'd certainly be way better than sharing the whole movie in SBS online, not to mention having a separate depth map could allow 3D strength customization and keep the door open for updated features like better haloing/gap fill algorithms or something.

**Comment by heyoeyo** [comment]
I completely forgot 3D blu-rays were a thing! It makes sense that there are already some standards for merging 2D/depth data together into video formats. Though maybe if built-in NPUs become commonplace, real-time conversion of 2D video to 3D depth maps will eventually just be a standard part of every video player, that'd be pretty cool.

**Comment by ThreeDeeJay** [comment]
yeah, Blu-ray 3D (MVC) is reasonably efficient for full HD 3D.
Here's the main/AVC track's filesize compared to the second view (MVC):
![image](https://github.com/user-attachments/assets/55bbf59d-291a-4fff-bef3-d9f6adcbdf71)
Decoding on PC can be tedious though (only a handful players support it) so I even had to put together a script here https://github.com/ThreeDeeJay/PotPlayer3D/releases/latest
