### ISSUE TITLE
Nitpicking Issue Not Affecting Performance

### ISSUE THREAD

**Issue by ktertikas** [DepthAnything/Depth-Anything-V2#71]
First of all thank you for the amazing work!

Just a bit of nitpicking here, but there seems to be two ReLU functions on the DepthAnythingv2 model, one in the `self.scratch.output_conv2` definition (see [here](https://github.com/DepthAnything/Depth-Anything-V2/blob/31dc97708961675ce6b3a8d8ffa729170a4aa273/depth_anything_v2/dpt.py#L113)), and one in the forward call (see [here](https://github.com/DepthAnything/Depth-Anything-V2/blob/31dc97708961675ce6b3a8d8ffa729170a4aa273/depth_anything_v2/dpt.py#L182)). I would suggest removing one of the two for clarity!

Best regards,
Konstantinos

**Comment by LiheYoung** [comment]
Thanks for the reminder. We will remove one in the next update.
