### ISSUE TITLE
I saw some news on Toutiao is that TikTok has launched version depthanthing v2, which is 10 times faster.

### ISSUE THREAD

**Issue by md5xwl** [DepthAnything/Depth-Anything-V2#9]
I saw some news on Toutiao is that TikTok has launched version depthanthing v2, which is 10 times faster.

So That's all fake news.???

**Comment by kagevazquez** [comment]
The quality that you can get from the smallest model is better than v1 and much faster to run. I can see it being 10x faster. Check out the paper they released and give it a try.

**Comment by Paper-Scallion** [comment]
The author says in the paper: "Compared with the latest models [31] built on Stable Diffusion, our models are significantly more efficient (more than 10× faster) and more accurate."
It is 10x faster than Stable Diffusion based models, not 10x faster than depth anything v1.
